### ISSUE TITLE
get() actually issues "gets" command on the wire

### ISSUE THREAD

**Issue by sapphirecat** [aio-libs/aiomcache#111]
This appears to be because [_multi_get()](https://github.com/aio-libs/aiomcache/blob/ca3e79e1bf1dd262835162da3748f5515046a48b/aiomcache/client.py#L78) defaults `with_cas=True` but the callers are all written as if the default were `with_cas=False`.

**Comment by Dreamsorcerer** [comment]
@thehesiod Any chance you want to investigate this?

**Comment by thehesiod** [comment]
one line fix, https://github.com/aio-libs/aiomcache/blob/ca3e79e1bf1dd262835162da3748f5515046a48b/aiomcache/client.py#L149 should pass with_case=False. I'd actually remove the default too
