### ISSUE TITLE
Passing loop argument to asyncio.Queue is deprecated since Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [aio-libs/aiomcache#196]
It seems the loop is passed if non-null or `get_event_loop` is called to get a loop. This generates a deprecation warning like below : 

```
aiomcache/pool.py:19: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    self._pool = asyncio.Queue(loop=loop)
```

https://github.com/aio-libs/aiomcache/blob/0f527db6660c6ce5e6c40ae806f2e8cfe624a894/aiomcache/pool.py#L19

**Comment by item4** [comment]
any update here?

**Comment by item4** [comment]
@achimnol

**Comment by item4** [comment]
any update yet? may i make pr about this?

**Comment by Dreamsorcerer** [comment]
#207
