### ISSUE TITLE
IndexError in get()

### ISSUE THREAD

**Issue by vmarkovtsev** [aio-libs/aiomcache#279]
We are using the latest release. Caught the following in Sentry in production:
![image](https://user-images.githubusercontent.com/2793551/185211962-fab5d1b8-267b-42de-85f3-be6de7317b4b.png)
![image](https://user-images.githubusercontent.com/2793551/185212099-654cb772-6645-45f3-9b91-72527cf0a18e.png)

We are running memcached on preemptible nodes in GCP and I suspect that the server died during `get()`.

**Comment by Dreamsorcerer** [comment]
I assume #307 is all that's needed to fix this. Would you like to sanity check that for me?

**Comment by vmarkovtsev** [comment]
I don't have a reproduction, unfortunately. We will use the new version, and I will report any further errors in the future. Thanks!
