### ISSUE TITLE
MANIFEST.in with CHANGES.txt

### ISSUE THREAD

**Issue by bloodbare** [aio-libs/aiomcache#36]
Hey congrats for the project, really interesting.

I'm having problems installing with source code, it would be possible to have a release with a MANIFEST.in that includes the CHANGES.txt and README.rst ? Its complaining that is missing it as its pointing on the setup.py and not released on the source package!

**Comment by jettify** [comment]
Somehow we missed manifest, created PR #37 with that file.

**Comment by fafhrd91** [comment]
Could you make new release?

**Comment by jettify** [comment]
sure

**Comment by jettify** [comment]
new version released https://pypi.python.org/pypi/aiomcache/0.5.1
