### ISSUE TITLE
param `max-line-length = 90` not working

### ISSUE THREAD

**Issue by ArtemIsmagilov** [aio-libs/aiomcache#405]
i try linting code.
run 
```bash
flake8 .
```
my code have line length ~100, but flake8 command no show this error.
i try change max-doc-length = 40 and this changes was raise error nut not  max-line-length = 40
Need fix this bug

**Comment by ArtemIsmagilov** [comment]
why ?ignore = E226, `E501`, E722, W503

**Comment by Dreamsorcerer** [comment]
> why ?

Read the comments?
https://github.com/aio-libs/aiomcache/blob/97039327bec1aca5c09e7268f9846cf376ff97ad/.flake8#L7-L10

**Comment by ArtemIsmagilov** [comment]
Indeed, I just didn't read the code carefully, I need to read the code more carefully.
