### ISSUE TITLE
Add python 3.5 support

### ISSUE THREAD

**Issue by Smirl** [aio-libs/aiomcache#7]
At the moment you cannot use the client with `await` python 3.5 syntax (at least not in the pypi version). The error that is returned is:
```
TypeError: object generator can't be used in 'await' expression
```

I think this can be fixed by decorating all of the coroutines with `asyncio.coroutine`. This is done in most places but not in the `aiomcache.client.acquire` decorator.

There might also be other places which mean it is not compatible with Python 3.5. I have "fixed" this in my code with: 
```
    self.client = aiomcache.Client(
            host,
            port,
            pool_size=pool_size,
            pool_minsize=pool_minsize,
            loop=loop
        )
        self.client.set = asyncio.coroutine(self.client.set)
        self.client.get = asyncio.coroutine(self.client.get)
        self.client.multi_get = asyncio.coroutine(self.client.multi_get)
```
Which isn't too pretty.

It would also be nice to create a new pypi version to add in the other cool things you guys have added since last year.

**Comment by asvetlov** [comment]
Fixed by #8
