### ISSUE TITLE
Open connections as needed instead of all at once

### ISSUE THREAD

**Issue by phette** [aio-libs/aiomcache#81]
The initial call to `acquire` a connection opens all connections up to the max size.  For anyone requiring a larger connection pool this becomes a relatively slow operation.  Depending on the efficiency of your application you may not need to have the max number of connections open anyways.  For those reasons I believe connections should be opened as needed until the max number of connections are reached.

https://github.com/aio-libs/aiomcache/blob/master/aiomcache/pool.py#L40-L44

**Comment by asvetlov** [comment]
It is a tradeoff between startup time and operation response one.
Please take a note that the client has two parameters: minimal and maximum size.
Setting the minimum size to non-zero value is very useful: it raises an exception if memcache server is not available on application startup (misconfiguration error most likely). 
It's better than a random failure on request processing.
